export class Countries {
    countriesJSON = [
        {name: 'Afghanistan', code: 'AF'},
        {name: 'Albania', code: 'AL'},
        {name: 'Algeria', code: 'DZ'},
        {name: 'American Samoa', code: 'AS'},
        {name: 'Antarctica', code: 'AQ'},
        {name: 'Australia', code: 'AU'},
        {name: 'Azerbaijan', code: 'AZ'},
        {name: 'Botswana', code: 'BW'},
        {name: 'Brazil', code: 'BR'},
        {name: 'Cameroon', code: 'CM'},
        {name: 'Canada', code: 'CA'},
        {name: 'China', code: 'CN'},
        {name: 'Congo, The Democratic Republic of the', code: 'CD'},
        {name: 'Denmark', code: 'DK'},
        {name: 'Ecuador', code: 'EC'},
        {name: 'Egypt', code: 'EG'},
        {name: 'Ethiopia', code: 'ET'},
        {name: 'Falkland Islands (Malvinas)', code: 'FK'},
        {name: 'France', code: 'FR'},
        {name: 'French Guiana', code: 'GF'},
        {name: 'Georgia', code: 'GE'},
        {name: 'Germany', code: 'DE'},
        {name: 'Ghana', code: 'GH'},
        {name: 'Greece', code: 'GR'},
        {name: 'Greenland', code: 'GL'},
        {name: 'Hong Kong', code: 'HK'},
        {name: 'Iceland', code: 'IS'},
        {name: 'India', code: 'IN'},
        {name: 'Indonesia', code: 'ID'},
        {name: 'Iran, Islamic Republic Of', code: 'IR'},
        {name: 'Iraq', code: 'IQ'},
        {name: 'Ireland', code: 'IE'},
        {name: 'Italy', code: 'IT'},
        {name: 'Japan', code: 'JP'},
        {name: 'Jordan', code: 'JO'},
        {name: 'Korea, Republic of', code: 'KR'},
        {name: 'Kuwait', code: 'KW'},
        {name: 'Lebanon', code: 'LB'},
        {name: 'Libyan Arab Jamahiriya', code: 'LY'},
        {name: 'Macao', code: 'MO'},
        {name: 'Madagascar', code: 'MG'},
        {name: 'Malaysia', code: 'MY'},
        {name: 'Maldives', code: 'MV'},
        {name: 'Mexico', code: 'MX'},
        {name: 'Moldova, Republic of', code: 'MD'},
        {name: 'Netherlands', code: 'NL'},
        {name: 'New Zealand', code: 'NZ'},
        {name: 'Nigeria', code: 'NG'},
        {name: 'Oman', code: 'OM'},
        {name: 'Pakistan', code: 'PK'},
        {name: 'Palestinian Territory, Occupied', code: 'PS'},
        {name: 'Paraguay', code: 'PY'},
        {name: 'Philippines', code: 'PH'},
        {name: 'Poland', code: 'PL'},
        {name: 'Portugal', code: 'PT'},
        {name: 'Qatar', code: 'QA'},
        {name: 'Romania', code: 'RO'},
        {name: 'Saudi Arabia', code: 'SA'},
        {name: 'Senegal', code: 'SN'},
        {name: 'Somalia', code: 'SO'},
        {name: 'South Africa', code: 'ZA'},
        {name: 'Spain', code: 'ES'},
        {name: 'Sudan', code: 'SD'},
        {name: 'Swaziland', code: 'SZ'},
        {name: 'Sweden', code: 'SE'},
        {name: 'Syrian Arab Republic', code: 'SY'},
        {name: 'Turkey', code: 'TR'},
        {name: 'Uganda', code: 'UG'},
        {name: 'Ukraine', code: 'UA'},
        {name: 'United Arab Emirates', code: 'AE'},
        {name: 'United Kingdom', code: 'GB'},
        {name: 'United States', code: 'US'},
        {name: 'Uruguay', code: 'UY'},
        {name: 'Virgin Islands, British', code: 'VG'},
        {name: 'Virgin Islands, U.S.', code: 'VI'},
        {name: 'Yemen', code: 'YE'},
        {name: 'Zambia', code: 'ZM'},
        {name: 'Zimbabwe', code: 'ZW'}
    ];
    countriesString = JSON.stringify(this.countriesJSON);
}
